ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/comm/manager.py", line 111, in comm_msg
    comm.handle_msg(msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 159, in handle_msg
    self._msg_callback(msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_nbagg.py", line 304, in on_message
    self.manager.handle_json(message)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_webagg_core.py", line 470, in handle_json
    self.canvas.handle_event(content)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_webagg_core.py", line 288, in handle_event
    self.draw()
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_webagg_core.py", line 179, in draw
    self.figure.draw(renderer)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2319, in draw
    a.draw(renderer)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 389, in draw
    im = self.make_image(renderer.get_image_magnification())
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 624, in make_image
    transformed_viewLim)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 237, in _get_unsampled_image
    x[..., 0:3] *= x[..., 3:4]
KeyboardInterrupt
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/comm/manager.py", line 111, in comm_msg
    comm.handle_msg(msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 159, in handle_msg
    self._msg_callback(msg)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_nbagg.py", line 304, in on_message
    self.manager.handle_json(message)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_webagg_core.py", line 470, in handle_json
    self.canvas.handle_event(content)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_webagg_core.py", line 288, in handle_event
    self.draw()
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_webagg_core.py", line 179, in draw
    self.figure.draw(renderer)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2319, in draw
    a.draw(renderer)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 389, in draw
    im = self.make_image(renderer.get_image_magnification())
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 624, in make_image
    transformed_viewLim)
  File "/home/oliver/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 237, in _get_unsampled_image
    x[..., 0:3] *= x[..., 3:4]
KeyboardInterrupt
